### ISSUE TITLE
SafeServiceClient is not multichain compatible

### ISSUE THREAD

**Issue by shredding** [gnosis/safe-core-sdk#120]
## Prerequisites

None.

## Description

If I sneak in the Network Tab in the Gnosis Frontend I can see that multi chain is supported in the API via `/chains/<id>`, e.g.:

`https://safe-client.gnosis.io/v1/chains/137/`

However, the service does not have a concept of [this](https://github.com/gnosis/safe-core-sdk/blob/main/packages/safe-service-client/src/utils/index.ts):

```
export function getTxServiceBaseUrl(txServiceUrl: string): string {
  return `${txServiceUrl}/api/v1`
}
```

I think something like this:

```typescript
const safeService = new SafeServiceClient('https://safe-client.gnosis.io', {
    chainId: 137
})

// down below

export function getTxServiceBaseUrl(txServiceUrl: string, {chainId}): string {
  const chainIdBits = chainId ? chains/${chainId}` : 'api'
  return `${txServiceUrl}/${chainIdBits}/v1`
}
```

would solve it.

Currently I receive a 404.

**Comment by germartinez** [comment]
Hello @shredding,

The SafeServiceClient is multichain compatible. This client consumes the Safe Transaction Service, that supports multiple networks:
- Mainnet => https://safe-transaction.gnosis.io/
- xDai => https://safe-transaction.xdai.gnosis.io/
- Polygon => https://safe-transaction.polygon.gnosis.io/
- ...

The confusion comes from the difference between the Safe Transaction Service (that has a different domain for each network) and the Safe Client Gateway (that also consumes the Safe Transaction Service but has a unified domain for all the networks).

As a note: Safe Client Gateway is a service that consumes the Safe Transaction Service and organizes the data to fit perfectly with our clients and it should not be used by anyone else, that is why the Safe Service Client consumes the Safe Transaction Service directly, to be used by the community.

For the example you provided (https://safe-client.gnosis.io/v1/chains/137/) you can check the `transactionService` property in the result to know what endpoint of the Safe Transaction Service is consuming: 
```
{
  "transactionService": "https://safe-transaction.polygon.gnosis.io",
  "chainId": "137",
  "chainName": "Polygon",
  "shortName": "matic",
  "l2": true,
  "description": "L2 chain (MATIC)",
  ...
```

Try with https://safe-client.gnosis.io/v1/chains/100/, for example, and a different endpoint will be displayed:

```
{
  "transactionService": "https://safe-transaction.xdai.gnosis.io",
  "chainId": "100",
  "chainName": "xDai",
  "shortName": "xdai",
  "l2": true,
  "description": "",
  ...
```

**Comment by germartinez** [comment]
It should be used like this:

```js
const safeServiceMainnet = new SafeServiceClient('https://safe-client.gnosis.io')

const safeServiceXDai = new SafeServiceClient('https://safe-client.xdai.gnosis.io')

...
```

**Comment by germartinez** [comment]
I'll make this more clear in the README

**Comment by shredding** [comment]
Thank you!

**Comment by shredding** [comment]
I have it now up and running and integrated. Great Library, keep it up.
