### ISSUE TITLE
Proposing a Safe transaction does not show in Gnosis UI transactions queue

### ISSUE THREAD

**Issue by marcin-trust** [gnosis/safe-core-sdk#130]
## Prerequisites

Proposing a tx as in https://github.com/gnosis/safe-core-sdk/blob/63df6c6c770f387f8e4939c4c75112ceb490b3b8/packages/guides/integrating-the-safe-core-sdk.md#5-propose-the-transaction-to-the-service

## Description

1. Propose a new multisig tx.
2. Wait up to 15 mins.
3. Tx not showing up in the queue in Gnosis Safe UI.
4. Confirm the tx using some of the owner account programmatically.
5. Tx shows up in the queue almost instantly.

Expected: Tx shows up in the queue right after proposing in order for owners to confirm it

## Environment

Rinkeby

"@gnosis.pm/safe-core-sdk": "^1.0.0",
"@gnosis.pm/safe-service-client": "^1.0.1",

**Comment by rmeissner** [comment]
The interface only shows transactions that have been confirmed by an owner or an delegate, to prevent that unauthorized parties can inject transactions.

**Comment by marcin-trust** [comment]
@rmeissner I understand, though questions still:
1. Can I propose with approval in a single step? Could the problem be that I propose with the Transaction Service (API) instead of the contract?
2. To my knowledge delegates CAN propose but they CANNOT approve. Is this a valid assumption? Could you point me to the docs/example how a delegate can approve?
