### ISSUE TITLE
deploySafe is failing with web3 adapter with error "gas" is missing

### ISSUE THREAD

**Issue by vigan-abd** [gnosis/safe-core-sdk#132]
## Description

When calling deploySafe method via web3 adapter the transaction is failing with error `Error: "gas" is missing`

## Environment

- Safe Core SDK version: ^1.2.0
- Safe contract version: 1.3.0-libs.0
- Environment:
  - non-browser (ubuntu 20.04.3 LTS, node v14.16.0, web3@1.6.1 dependency and ethers@5.5.2)

## Steps to reproduce

sample js script to produce the issue
```js
'use strict'

const Web3 = require('web3')
const { Web3Adapter, SafeFactory } = require('@gnosis.pm/safe-core-sdk')

const privKeys = [
  '....',
  '....',
  '....',
]

/**
 * 
 * @param {Web3.default} web3 
 */
const main = async (web3) => {
  const [acc1, acc2, acc3] = privKeys.map(privKey => web3.eth.accounts.privateKeyToAccount(privKey))
  web3.eth.accounts.wallet.add({
    address: acc1.address,
    privateKey: acc1.privateKey
  })

  const acc1Adapter = new Web3Adapter({
    web3: web3,
    signerAddress: acc1.address
  })

  const safeFactory = await SafeFactory.create({
    ethAdapter: acc1Adapter,
    safeVersion: '1.3.0',
    contractNetworks: {
      '1337': { // I've added manually local ganache-cli network into safe-deployed dependency
        multiSendAddress: '0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761',
        safeMasterCopyAddress: '0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552',
        safeProxyFactoryAddress: '0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2'
      }
    },
    isL1SafeMasterCopy: true // NOT L2 Network
  })

  const safe = await safeFactory.deploySafe({ // this one throws because of missing gas
    owners: [acc1.address, acc2.address, acc3.address],
    threshold: 2
  })

  console.log(safe.getAddress())
}

const web3 = new Web3(new Web3.providers.HttpProvider('http://127.0.0.1:7545'))
main(web3).catch(console.error)

```

P.S. I've first deployed contracts on ganache-cli and then tested this script

## Expected result

I've expected safe to be deployed but it's failing because gas is missing, according to https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-send gas/gasPrice are optional but seems to fail in my env

## Additional context

Off topic, but I also had to install ethers dependency manually otherwise package didn't work because ethers is under devDependencies section, I think you should move it on dependencies section since it's required by common-js loader

**Comment by vigan-abd** [comment]
hello Gnosis team, thanks for awesome work that you're doing :)
Re issue above, I can open a PR with a fix related to issue but first wanted to confirm with you guys if it's ok to do it

My solution would be to use [estimateGas](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-estimategas) method and pass gas determined by there, or if gas could be optional param provided into method then estimategas could be omitted. I think also exposing gas and gasPrice options to method call would be nice because sometimes people want to put higher priority into their transactions

P.S I'm not sure if this issue occurs also with metamask web3 lib

**Comment by vigan-abd** [comment]
Also noticed another issue with event fetching, you're always fetching first entry however the order of events might be different:
```
{
  '0': {
    logIndex: 0,
    transactionIndex: 0,
    transactionHash: '0xe0459c43508d18e54b2a9ea30f4d3254a28cae76a6db156a0a7ceedc2eed71fd',
    blockHash: '0x82cd2f590ad98905e639d9cde300cd69372debaea2706f4365d13c8fbdfc0476',
    blockNumber: 18,
    address: '0x8bcd5762980317a20A59f4885320c6dfc9086Ec0',
    type: 'mined',
    removed: false,
    id: 'log_2b0458b9',
    returnValues: Result {},
    event: undefined,
    signature: null,
    raw: {
      data: '0x00000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000b5e803a89621300d55aed43f7a8579b7c55709fe0000000000000000000000000b7f77ac35fc823b07e7e67aba8d864acb7716560000000000000000000000004dd07611d01527aec3a29c1b56e2227a7c5996e5',
      topics: [Array]
    }
  },
  ProxyCreation: {
    logIndex: 1,
    transactionIndex: 0,
    transactionHash: '0xe0459c43508d18e54b2a9ea30f4d3254a28cae76a6db156a0a7ceedc2eed71fd',
    blockHash: '0x82cd2f590ad98905e639d9cde300cd69372debaea2706f4365d13c8fbdfc0476',
    blockNumber: 18,
    address: '0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2',
    type: 'mined',
    removed: false,
    id: 'log_5e253cfd',
    returnValues: Result {
      '0': '0x8bcd5762980317a20A59f4885320c6dfc9086Ec0',
      '1': '0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552',
      proxy: '0x8bcd5762980317a20A59f4885320c6dfc9086Ec0',
      singleton: '0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552'
    },
    event: 'ProxyCreation',
    signature: '0x4f51faf6c4561ff95f067657e43439f0f856d97c04d9ec9070a6199ad418e235',
    raw: {
      data: '0x0000000000000000000000008bcd5762980317a20a59f4885320c6dfc9086ec0000000000000000000000000d9db270c1b5e3bd161e8c8503c55ceabee709552',
      topics: [Array]
    }
  }
}
```

The issue is occurring on safe-core-sdk/packages/safe-core-sdk/src/contracts/GnosisSafeProxyFactory/GnosisSafeProxyFactoryWeb3Contract.ts#L26 (const proxyAddress = txResult.events?.['0'].raw?.data.substr(-40))

**Comment by germartinez** [comment]
Hi @vigan-abd, regarding the additional topic, are you referring to some @ethersproject sub-modules?

**Comment by vigan-abd** [comment]
Hi @germartinez , I just tried to install the dependency  via npm into a local project `npm i @gnosis.pm/safe-core-sdk` and after importing it, it was throwing error ethers module not found. Then I had to install ethers also so it could detect the dependency

**Comment by c-jain** [comment]
Hi guys, can we fix this issue asap? Actually, it is a blocker for us to use SDK in the backend.
