### ISSUE TITLE
SafeTxGas bug introduced in v1.2.0

### ISSUE THREAD

**Issue by webmodularity** [gnosis/safe-core-sdk#139]
## Description

As brought up in (https://ethereum.stackexchange.com/questions/118024/safetxgas-always-ends-up-being-0-which-causes-revert-inside-multisend-contract) and (https://ethereum.stackexchange.com/questions/117704/out-of-gas-revert-inside-the-multisend-contract) the safeTxGas gas value will be set to 0 regardless of what is specified in `options`. safeTxGas is the only option that gets ignored.

## Environment

safe-core-sdk >= 1.2.0

## Steps to reproduce

Create a fresh project and install safe-core-sdk `npm install @gnosis.pm/safe-core-sdk`.

```   
    const multiSendTx = [
        {
            to: zrxERC20Rinkeby,
            data: erc20Interface.encodeFunctionData("transfer", [
                recipient1,
                ethers.BigNumber.from(10).pow(18).mul(1),
            ]),
            value: "0",
        },
        {
            to: BATERC20Rinkeby,
            data: erc20Interface.encodeFunctionData("transfer", [
                recipient1,
                ethers.BigNumber.from(10).pow(18).mul(1),
            ]),
            value: "0",
        }
    ];
    const txOptions = {
        safeTxGas: 150000,
        baseGas: 60000,
        refundReceiver: signer.address,
        gasPrice: 2500000000
    };
    const safeTransaction = await safeSdk.createTransaction(multiSendTx, txOptions);
```

Using any combination of multiSendTx or txOptions results in the same behavior that zeroes out safeTxGas inside the createTransaction() method.

## Expected result

Expected `safeTransaction {safeTxGas:  150000}` but get `safeTransaction {safeTxGas:  0}`

## Additional context

The issue is resolved by forcing v1.1.1 of safe-core-sdk. `"@gnosis.pm/safe-core-sdk": "1.1.1"`

Thanks for looking into this.
Rory | Paymagic

**Comment by ryan-eiv** [comment]
I'm still getting this issue with v2.0.0

**Comment by germartinez** [comment]
@ryan-eiv if you want to specify the safeTxGas in a Safe>=v1.3.0, you also need to specify gasPrice.
https://github.com/gnosis/safe-contracts/blob/a6504a9afdeac186a8cdb29ad68b189523c80eda/docs/safe_tx_gas.md

If Safe>=v1.3.0 and gasPrice=0, safeTxGas will be 0
If Safe>=v1.3.0 and gasPrice > 0, safeTxGas will be the specified or it will be estimated in the SDK
If Safe<v1.3.0, safeTxGas will be the specified or it will be estimated in the SDK

**Comment by ryan-eiv** [comment]
got it, thanks! I think there's still an issue with safes that are contract version 1.1.1 but I'll write a separate Issue

**Comment by Gabriel-Mbugua** [comment]
Hi @webmodularity or @germartinez, any updates on the versioning for @safe-global/protocol-kit? I saw that @gnosis.pm/safe-core-sdk has been migrated to @safe-global/protocol-kit now but not sure which version resolves the issue above.
