### ISSUE TITLE
generateSignature build error

### ISSUE THREAD

**Issue by greyireland** [gnosis/safe-core-sdk#141]
## Description

I want to use this function `generateSignature(this.#ethAdapter, hash)`,but when run tsc,get this error:
```
> tsc

node_modules/@gnosis.pm/safe-core-sdk/dist/src/utils/signatures/index.d.ts:2:24 - error TS2307: Cannot find module 'ethereumLibs/EthAdapter' or its corresponding type declarations.

2 import EthAdapter from 'ethereumLibs/EthAdapter';
```

## Environment
    "@gnosis.pm/safe-core-sdk": "^1.1.1",
    "@gnosis.pm/safe-core-sdk-types": "^0.1.1",

**Comment by germartinez** [comment]
Hi @greyireland,
The `generateSignature` function is not exported, it's only used internally in the SDK.

**Comment by greyireland** [comment]
Thks,I use signTransactionHash instead.
