### ISSUE TITLE
safeService.getAllTransactions is not a function

### ISSUE THREAD

**Issue by davidthomasparks** [gnosis/safe-core-sdk#143]
## Description

I am trying to use the newly implemented getAllTransactions function but it is saying it's not found. I see that you merged a few weeks ago but not sure if this made it into the 1.0.1 build on NPM. 

## Steps to reproduce

Try to use the safeService 1.0.1 version and use getAllTransactions

## Expected result

It should return all safe transactions

**Comment by germartinez** [comment]
Hi @davidthomasparks!
v1.1.0 is now released (https://www.npmjs.com/package/@gnosis.pm/safe-service-client)
