### ISSUE TITLE
Installing from npm does not install all needed dependencies

### ISSUE THREAD

**Issue by ryan-eiv** [gnosis/safe-core-sdk#152]
## Description

Installing with `npm install @gnosis.pm/safe-core-sdk` does not install needed dependencies like `@ethersproject/solidity` and `ethers`

## Environment

- Safe Core SDK version: 1.3.0
- Safe contract version: n/a
- Environment: browser

## Steps to reproduce

1. install with
2. try to use `Safe` and `Web3Adapter`: `import Safe, { Web3Adapter } from '@gnosis.pm/safe-core-sdk';`
3. Get error: `Module not found: Can't resolve 'ethers'`

## Expected result

I expect there should be no missing dependencies.

**Comment by ryan-eiv** [comment]
thank you!

**Comment by germartinez** [comment]
To be released early next week :)
