### ISSUE TITLE
Please TAG PR #156

### ISSUE THREAD

**Issue by datradito** [gnosis/safe-core-sdk#157]
## Description

Please tag the PR [https://github.com/gnosis/safe-core-sdk/pull/156](url), to be able to install the safe-development version needed to moonbeam.

https://github.com/gnosis/safe-core-sdk/blob/main/packages/safe-core-sdk/package.json
![image](https://user-images.githubusercontent.com/19674406/151047893-fe274c38-a685-47f1-ae83-e1e001035085.png)

CC: @germartinez

**Comment by germartinez** [comment]
@datradito Hi, a new release of the SDK was published adding this feature
