### ISSUE TITLE
getModuleTransactions in the safe-service-client does not work

### ISSUE THREAD

**Issue by de33** [gnosis/safe-core-sdk#172]
## Description

getModuleTransactions as referred to here https://github.com/gnosis/safe-core-sdk/tree/main/packages/safe-service-client#getmoduletransactions in the safe-service-client does not work

## Environment

- Safe Core SDK version: 2.0.0
- Safe contract version: 1.3.0
- Environment:
  - non-browser

## Steps to reproduce

When I run this script: 

```
const {
  default: SafeServiceClient,
} = require("@gnosis.pm/safe-service-client");

const safe = "0x07545567fAfF5ce6bA9a1B6345b57F162099AC64";

async function main() {
  const serviceRinkebyUrl = "https://safe-transaction.rinkeby.gnosis.io/";
  const safeService = new SafeServiceClient(serviceRinkebyUrl);

  const moduleTxs = await safeService.getModuleTransactions(safe);

  console.log(moduleTxs);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });



```
I get:
```
 Error: Not Found
    at sendRequest (/Users/david/node_modules/@gnosis.pm/safe-service-client/dist/src/utils/httpRequests.js:29:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/Users/david/gnosis-tests/tests/mod-tx-test.js:14:21)
```

## Expected result

Expect transactions data including a results array of transactions from modules on the safe, similar to getAllTransactions and getMultisigTransactions

**Comment by rmeissner** [comment]
The url in https://github.com/gnosis/safe-core-sdk/blob/main/packages/safe-service-client/src/SafeServiceClient.ts#L415 is incorrect. it should be `module-transactions` instead of `module-transfers`.

E.g. https://safe-transaction.rinkeby.gnosis.io/api/v1/safes/0x07545567fAfF5ce6bA9a1B6345b57F162099AC64/module-transactions/

**Comment by de33** [comment]
Thanks for the fast response @rmeissner 🙏
