### ISSUE TITLE
Coin will be withdrawn from my personal wallet, not from the safe.

### ISSUE THREAD

**Issue by YoonYoungDoo** [gnosis/safe-core-sdk#175]
I am still learning about the blockchain.

I succeeded in accessing Safe made using my wallet's Private Key,
Now, we are trying to implement the function of withdrawing Ethereum from Safe to another person's wallet.

Owner in Safe is me alone.
In safeSdk, the balance for my safe is normally inquired.
But when I operate the following code, Ethereum is withdrawn from my personal wallet.
What am I missing?

```js
import Safe, { EthSignSignature } from '@gnosis.pm/safe-core-sdk'
import { SafeService, SafeEthersSigner } from '@gnosis.pm/safe-ethers-adapters'
import { ethers } from 'ethers'
import EthersAdapter, { EthersTransactionOptions } from '@gnosis.pm/safe-ethers-lib'
import { Wallet } from '@ethersproject/wallet'
import { SafeTransactionDataPartial, SafeTransactionData  } from '@gnosis.pm/safe-core-sdk-types'
import SafeServiceClient, { OwnerResponse, ProposeTransactionProps, SafeMultisigTransactionResponse, SafeBalanceResponse } from "@gnosis.pm/safe-service-client";
const safeService = new SafeServiceClient('https://safe-transaction.rinkeby.gnosis.io');

(async() => {
 try {
  const Web3 = require('web3')

  const privateKey = "0xPRIVATEKEYPRIVATEKEYPRIVATEKEYPRIVATEKEYPRIVATEKEYPRIVATEKEY";
  const safeAddress = '0xSAFEADDRESSSAFEADDRESSSAFEADDRESSSAFEADDRESSSAFEADDRESS'
  const _web3 = new Web3.providers.HttpProvider("https://rinkeby.infura.io/v3/MYAPIKEY");
  const web3Provider = _web3
  const provider = new ethers.providers.Web3Provider(web3Provider)
  const service = new SafeService("https://safe-transaction.rinkeby.gnosis.io")
  const signer = new Wallet(privateKey, provider)
  const ethAdapter = new EthersAdapter({ ethers, signer })
  const safe: Safe = await Safe.create({ ethAdapter, safeAddress: safeAddress })
  const safeSigner = new SafeEthersSigner(safe, service, provider)
  const address = safe.getAddress()
  const owners = await safe.getOwners()
  const balance = await safe.getBalance()

  const transaction: SafeTransactionDataPartial = {
    to: '0xANOTHERWALLETADDRESSANOTHERWALLETADDRESSANOTHERWALLETADDRESS',
    value: '1',
    data: '0x'
  }

  const safeTransaction = await safe.createTransaction(transaction)
  await safe.signTransaction(safeTransaction)

  const safeTxHash = await safe.getTransactionHash(safeTransaction)
  await safeService.proposeTransaction({
    safeAddress,
    safeTransaction,
    safeTxHash,
    senderAddress: '0xMYWALLETADDRESSMYWALLETADDRESSMYWALLETADDRESS'
  })

  let signature = await safe.signTransactionHash(safeTxHash)
  await safeService.confirmTransaction(safeTxHash, signature.data)
  const tx: SafeMultisigTransactionResponse = await safeService.getTransaction(safeTxHash)
  const safeTransactionData: SafeTransactionData = {
    to: tx.to,
    value: tx.value,
    data: '0x',
    operation: tx.operation,
    safeTxGas: tx.safeTxGas,
    baseGas: tx.baseGas,
    gasPrice: Number(tx.gasPrice),
    gasToken: tx.gasToken,
    refundReceiver: String(tx.refundReceiver),
    nonce: tx.nonce
  }
  const safeTransaction2 = await safe.createTransaction(safeTransactionData)
  const executeTxResponse = await safe.executeTransaction(safeTransaction2)
  const receipt = executeTxResponse.transactionResponse && (await executeTxResponse.transactionResponse.wait())
  console.log(receipt)
 }catch(e) {

 }
})();
```

**Comment by YoonYoungDoo** [comment]
Hi @germartinez 
I changed it to the code you delivered and tested it.
0.1 Ethereum was set as follows,
`
  const transaction: SafeTransactionDataPartial = {
    to: '0xANOTHERWALLETADDRESSANOTHERWALLETADDRESSANOTHERWALLETADDRESS',
    value: '100000000000000000', //0.1ETH
    data: '0x'
  }
`
The Ethereum I wanted from the safe escaped to Another Address. (0.1ETH)
But the Ethereum in my personal wallet have decreased a little. (0.0002ETH)
Is this a gasfee?
Isn't the gasfee paid in the safe?

It may be a very obvious question, but thank you for your help.

**Comment by germartinez** [comment]
Yes, that is expected.

0.0002 ETH was the gas fee, that is paid by the executor when sending the transaction to the Safe.

However, if you add to the transaction the following properties, the gas spent can be refunded from the Safe to the specified address:
- `gasToken`: 0x address to refund Ethereum, or a token address to refund that token. The Safe needs to have enough balance to send the transaction `value` and the refund amount.
- `refundReceiver`: the address that is going to be refunded. Usually the address that executes the transaction and pays the gas in advance.

This way the owner pays the gas for the transaction, but at the end the Safe pays back the fees to that address, but it looks like the transaction fees were paid by the Safe.

**Comment by YoonYoungDoo** [comment]
My question has been solved.
Thank you.
I hope you have a good day.
