### ISSUE TITLE
Is there a way to avoid internal transactions?

### ISSUE THREAD

**Issue by YoonYoungDoo** [gnosis/safe-core-sdk#186]
Currently, token transmission is normally performed using the SDK.
The balance of the target wallet also increases normally.

`const transaction: SafeTransactionDataPartial = {
            to: toAddress,
            value: sendValue,
            data: "0x",
            gasPrice: Web3.utils.toWei("50", "gwei")
        }
        const safeTransaction = await safe.createTransaction(transaction)
        const options: EthersTransactionOptions  = {
          gasPrice: Web3.utils.toWei("50", "gwei")
        }
        const executeTxResponse = await safe.executeTransaction(safeTransaction, options)
        const txResponse = await executeTxResponse.transactionResponse?.wait()`

However, as shown in the screenshot below, transmission through internal transactions does not appear to accurately express history.
![스크린샷 2022-03-24 오후 5 25 05](https://user-images.githubusercontent.com/29750432/159874064-026c5853-1761-449b-aa5d-2c55ae87cb43.png)

To avoid this situation, I would like to create a general transaction as follows.
![스크린샷 2022-03-24 오후 5 28 52](https://user-images.githubusercontent.com/29750432/159874409-f3ebcb4c-66fa-48a3-b28c-f49cee334fe9.png)

Is there a way?
Thank you for your help.

**Comment by rmeissner** [comment]
This is not possible with the Safe (or any other smart contract). As what you mention as a "general transaction" can only be created with a private key, which does not exist for smart contracts. Therefore any interaction (ETH transfer, token transfer or other contract call) from the Safe (or another smart contract) will be an internal transaction.

To get more detailed information on this I would recommend posting this question on https://ethereum.stackexchange.com
