### ISSUE TITLE
Allow the creation of new Safes

### ISSUE THREAD

**Issue by germartinez** [gnosis/safe-core-sdk#27]
TBD: Check https://github.com/rsksmart/safe-core-sdk/pull/1 and https://github.com/rsksmart/safe-core-sdk/pull/2

**Comment by byterose** [comment]
## Description

I got the following error after building and calling the createSafe method in develop of the [rsksmart safe-core-sdk](https://github.com/rsksmart/safe-core-sdk/tree/develop) fork.
> EthersSafeFactory.ts:104 Uncaught (in promise) TypeError: Cannot read property 'args' of undefined
    at EthersSafeFactory.deployProxy (EthersSafeFactory.ts:104)

## Environment

- Environment: node (svelte)

## Steps to reproduce

1. ```yarn build```
2. Implement node_module in a project
3. Follow the instructions in the README to create a safe

## Expected result

It should be able to create a safe as described in the tests

## Additional context

I assume this has something to do with the build as the tests are passing while the method throws an error when I try to call the method in /dist after the build. 
The error probably results from the following line: https://github.com/rsksmart/safe-core-sdk/blob/develop/src/EthersSafeFactory.ts#L104

**Comment by ilanolkies** [comment]
Hi @byterose! We are now working for _safe creations_ in this repo: https://github.com/rsksmart/safe-factory-sdk We are going to publish it to npm very soon.
