### ISSUE TITLE
Add rejectTransaction method to the Safe Core SDK

### ISSUE THREAD

**Issue by germartinez** [gnosis/safe-core-sdk#32]
The developer would call `safeSdk.rejectTransaction(safeTransaction)` to propose the rejection of a transaction. Similar to `signTransaction` but saving the rejection signatures associated to the transaction.

**Comment by ilanolkies** [comment]
Hi team. For this we are currently using this method

https://github.com/rsksmart/safe-transactions-sdk/blob/85e93a4e9632c16414f4a95aace748bebe1a1f7a/src/utils/reject.ts#L4
