### ISSUE TITLE
Remove ethers from constructor and add it as a peer dependency

### ISSUE THREAD

**Issue by germartinez** [gnosis/safe-core-sdk#33]
Remove ethers from constructor and add it as a peer dependency

**Comment by mikheevm** [comment]
I remember we talked about this when starting the SDK and it was not obvious that this is a better/easier approach. Curious why did you decide to do so?

**Comment by rmeissner** [comment]
Currently the sdk is incosistent. For the utils the `ethers` object passed in the constructor is used and in a lot of other places dependencies are directly used (e.g. via `@ethersproject` imports). 

The `@ethersproject` imports allow it to be very specific on what is being imported (compared to just importing all of `ethers` which includes wordlist and many other things). 

The purpose of passing in an `ethers` instance is that the user is in control what version is used, but this should also be possible via a peer dependency. And this way you can take full advantage of typescript, which is currently not possible as the passed in `ethers` instance is of type `any`
