### ISSUE TITLE
safe-core-sdk README outdated

### ISSUE THREAD

**Issue by antomor** [gnosis/safe-core-sdk#55]
The README of the `safe-core-sdk` package is outdated, and it doesn't include the changes related to the introduction of the `TransactionResult` interface. 
All the examples with `execute` or `approveTransactionHash` call the `wait` method on the `TransactionResult` interface, but it doesn't include such method.

**Example**

Wrong version:
```js
const approveTxResponse = await safeSdk2.approveTransactionHash(txHash)
await approveTxResponse.wait()
```

Fixed version:
```js
const executeTxResponse = await safeSdk3.executeTransaction(safeTransaction)
await executeTxResponse.transactionResponse?.wait()
```

**Comment by germartinez** [comment]
Good catch @antomor. Thank you very much!
