### ISSUE TITLE
How to initiate transactions that can be signed in the Gnosis UI?

### ISSUE THREAD

**Issue by cj-l** [gnosis/safe-core-sdk#63]
Hi, I'm hoping you can help with the usage of this repo.

I (as one of the safe owners) am looking to programmatically initiate a transaction that the other safe owners can sign in the Gnosis UI.

Is this SDK the best way to achieve that?

**Comment by germartinez** [comment]
Hello @cj-l,

Inside this monorepo you will find two packages to achieve that: `safe-core-sdk` and `safe-service-client`

Use the `safe-core-sdk` to create a transaction object (`.createTransaction(...)`) and the `safe-service-client` to send it to the service (`.proposeTransaction(...)`) to make it available on the UI

**Comment by cj-l** [comment]
Thanks @germartinez 

I'm attempting to do the above in a hardhat script and running into some trouble.
To use `.createTransaction` I need an instance of `Safe` from `safe-core-sdk`.

I'm attempting to do this as follows

```
let provider = new ethers.providers.InfuraProvider(
    chainId, infuraKey
  )
const owner = provider.getSigner()
const ethAdapterOwner = new EthersAdapter({
    ethers,
    signer: owner
  })
const safeSdk: Safe = await Safe.create({
    ethAdapter: ethAdapterOwner, 
    safeAddress: safeAddress,
  })
```

However understandably ethers' `InfuraProvider` is failing to run `getSigner`, I assume because infura doesn't have access to my private key.

I see that in the `safe-core-sdk` readme it's recommended to use `ethers.providers.Web3Provider(web3Provider)`, but would this only work in a frontend application where for example metamask is available as the web3Provider? 

Can you recommend a way to do this within a hardhat script?

Thanks

**Comment by cj-l** [comment]
Thanks @germartinez.

I'm trying to get this working in a hardhat script and having some issues.

1. Imports
I've been unable to import types as recommended by the readme:
```
import { SafeTransactionDataPartial } from '@gnosis.pm/safe-core-sdk'
```
As it fails with `Module '"@gnosis.pm/safe-core-sdk"' has no exported member 'SafeTransactionDataPartial'.` Instead I'm doing  this, which seems to work:
```
import { SafeTransactionData, SafeSignature } from '@gnosis.pm/safe-core-sdk-types'
```
2.  Proposing a transaction
The readme suggests the following
```
await safeService.proposeTransaction(safeAddress, transaction, safeTxHash, signature)
```
Where am I supposed to get the `safeTxHash` for this?
Also, I'm trying to create a `SafeSignature`, but get the following error:
```
Type '{ signer: string; data: string; }' is missing the following properties from type 'SafeSignature': staticPart, dynamicPart
```
Could you tell me what `staticPart` and `dynamicPart` are supposed to be?

I'm not sure if it's relevant, but I'm installing these packages with `@gnosis.pm/safe-service-client`, rather than install local copies of the repos. Is that okay?

**Comment by germartinez** [comment]
Hi @cj-l,

`SafeTransactionDataPartial` is exported from  `@gnosis.pm/safe-core-sdk-types` instead of `@gnosis.pm/safe-core-sdk`
