### ISSUE TITLE
Set custom/optional parameters in MultiSend transaction

### ISSUE THREAD

**Issue by germartinez** [gnosis/safe-core-sdk#73]
## Description

When creating a multisend transaction the user is not allowed to set the optional params included in `SafeTransactionDataPartial` (`safeTxGas`, `baseGas`, `gasPrice`, `gasToken`, `refundReceiver` and `nonce`).

## Environment

- Safe Core SDK last version

## Expected result

The user is allowed to set the optional params included in `SafeTransactionDataPartial` (`safeTxGas`, `baseGas`, `gasPrice`, `gasToken`, `refundReceiver` and `nonce`) when creating a multisend transaction.

**Comment by justinjmoses** [comment]
Do you envisage it just be an additional argument to `Safe.createTransaction()` ?

**Comment by germartinez** [comment]
Hi @justinjmoses
Just adding the `options` parameter for the multisend transaction:
```
function createTransaction(tx: SafeTransactionDataPartial, options: undefined)
function createTransaction(tx: MetaTransactionData[], options?: SafeTransactionDataPartial)
```

**Comment by justinjmoses** [comment]
Awesome. Looking forward to the next release.
