### ISSUE TITLE
Error in documentation of safe-core-sdk

### ISSUE THREAD

**Issue by cmdzro** [gnosis/safe-core-sdk#97]
## Description

The documentation of the `safe-core-sdk` has an error in the `API Reference` / `connect` section:
https://github.com/gnosis/safe-core-sdk/tree/main/packages/safe-core-sdk#api-reference

The code sample for the `contractNetworks` property was probably copy-pasted from the `create` section. I assume it should use `connect` instead of `create`.

## Expected result

Documentation should read like:

```
const safeSdk = await Safe.connect({ ethAdapter, safeAddress, contractNetworks })
```

**Comment by germartinez** [comment]
True! Thank you for the catch! :)
